version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: xpc-emr-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: xpc_emr
      POSTGRES_PASSWORD: xpc_emr_dev_password
      POSTGRES_DB: xpc_emr
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
