// @vitest-environment node
import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock all 15 FHIR service modules
vi.mock('@/lib/services/fhir-medication-service', () => ({
  searchFhirMedications: vi.fn(),
}))
vi.mock('@/lib/services/fhir-allergy-service', () => ({
  searchFhirAllergies: vi.fn(),
}))
vi.mock('@/lib/services/fhir-condition-service', () => ({
  searchFhirConditions: vi.fn(),
}))
vi.mock('@/lib/services/fhir-lab-service', () => ({
  searchFhirLabOrders: vi.fn(),
}))
vi.mock('@/lib/services/fhir-imaging-service', () => ({
  searchFhirImagingOrders: vi.fn(),
}))
vi.mock('@/lib/services/fhir-goal-service', () => ({
  searchFhirGoals: vi.fn(),
}))
vi.mock('@/lib/services/fhir-care-team-service', () => ({
  searchFhirCareTeamMembers: vi.fn(),
}))
vi.mock('@/lib/services/fhir-social-history-service', () => ({
  searchFhirSocialHistories: vi.fn(),
}))
vi.mock('@/lib/services/fhir-family-history-service', () => ({
  searchFhirFamilyHistories: vi.fn(),
}))
vi.mock('@/lib/services/fhir-procedure-service', () => ({
  searchFhirProcedures: vi.fn(),
}))
vi.mock('@/lib/services/fhir-referral-service', () => ({
  searchFhirReferrals: vi.fn(),
}))
vi.mock('@/lib/services/fhir-vital-service', () => ({
  searchFhirVitals: vi.fn(),
}))
vi.mock('@/lib/services/fhir-task-service', () => ({
  searchFhirTasks: vi.fn(),
}))
vi.mock('@/lib/services/fhir-encounter-service', () => ({
  searchFhirEncounters: vi.fn(),
}))
vi.mock('@/lib/services/fhir-appointment-service', () => ({
  searchFhirAppointmentsByPatient: vi.fn(),
}))

import { buildPatientVariables } from '@/lib/variable-formatters'
import { searchFhirMedications } from '@/lib/services/fhir-medication-service'
import { searchFhirAllergies } from '@/lib/services/fhir-allergy-service'
import { searchFhirConditions } from '@/lib/services/fhir-condition-service'
import { searchFhirLabOrders } from '@/lib/services/fhir-lab-service'
import { searchFhirImagingOrders } from '@/lib/services/fhir-imaging-service'
import { searchFhirGoals } from '@/lib/services/fhir-goal-service'
import { searchFhirCareTeamMembers } from '@/lib/services/fhir-care-team-service'
import { searchFhirSocialHistories } from '@/lib/services/fhir-social-history-service'
import { searchFhirFamilyHistories } from '@/lib/services/fhir-family-history-service'
import { searchFhirProcedures } from '@/lib/services/fhir-procedure-service'
import { searchFhirReferrals } from '@/lib/services/fhir-referral-service'
import { searchFhirVitals } from '@/lib/services/fhir-vital-service'
import { searchFhirTasks } from '@/lib/services/fhir-task-service'
import { searchFhirEncounters } from '@/lib/services/fhir-encounter-service'
import { searchFhirAppointmentsByPatient } from '@/lib/services/fhir-appointment-service'

function mockAllServicesEmpty() {
  vi.mocked(searchFhirMedications).mockResolvedValue({ medications: [] })
  vi.mocked(searchFhirAllergies).mockResolvedValue({ allergies: [] })
  vi.mocked(searchFhirConditions).mockResolvedValue({ conditions: [] })
  vi.mocked(searchFhirLabOrders).mockResolvedValue({ labOrders: [] })
  vi.mocked(searchFhirImagingOrders).mockResolvedValue({ imagingOrders: [] })
  vi.mocked(searchFhirGoals).mockResolvedValue({ goals: [] })
  vi.mocked(searchFhirCareTeamMembers).mockResolvedValue({ members: [] })
  vi.mocked(searchFhirSocialHistories).mockResolvedValue({ observations: [] })
  vi.mocked(searchFhirFamilyHistories).mockResolvedValue({ members: [] })
  vi.mocked(searchFhirProcedures).mockResolvedValue({ procedures: [] })
  vi.mocked(searchFhirReferrals).mockResolvedValue({ referrals: [] })
  vi.mocked(searchFhirVitals).mockResolvedValue({ vitals: [] })
  vi.mocked(searchFhirTasks).mockResolvedValue({ tasks: [] })
  vi.mocked(searchFhirEncounters).mockResolvedValue({ encounters: [] })
  vi.mocked(searchFhirAppointmentsByPatient).mockResolvedValue({ appointments: [] })
}

describe('buildPatientVariables', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockAllServicesEmpty()
  })

  it('returns exactly 16 variables', async () => {
    const vars = await buildPatientVariables('fhir-123')
    expect(Object.keys(vars)).toHaveLength(16)
  })

  it('all variables have required fields', async () => {
    const vars = await buildPatientVariables('fhir-123')
    for (const v of Object.values(vars)) {
      expect(v).toHaveProperty('name')
      expect(v).toHaveProperty('content')
      expect(v).toHaveProperty('icon')
      expect(v).toHaveProperty('isAutoGenerated', true)
      expect(v).toHaveProperty('lastRefreshedAt')
      expect(typeof v.lastRefreshedAt).toBe('number')
    }
  })

  it('includes correct variable keys', async () => {
    const vars = await buildPatientVariables('fhir-123')
    const expectedKeys = [
      'patient_info', 'medications', 'allergies', 'conditions', 'vitals',
      'care_team', 'goals_of_care', 'labs', 'imaging', 'surgical_history',
      'family_history', 'social_history', 'referrals', 'tasks', 'encounters',
      'appointments',
    ]
    for (const key of expectedKeys) {
      expect(vars).toHaveProperty(key)
    }
  })

  it('shows "No ... on file" for empty data', async () => {
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.medications.content).toContain('No medications on file')
    expect(vars.allergies.content).toContain('No allergies on file')
    expect(vars.conditions.content).toContain('No conditions on file')
    expect(vars.vitals.content).toContain('No vitals on file')
    expect(vars.labs.content).toContain('No lab orders on file')
  })

  it('shows "No patient data available" when no patient provided', async () => {
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.patient_info.content).toContain('No patient data available')
  })

  it('formats patient demographics when patient provided', async () => {
    const patient = { id: '1', name: 'John Doe', dob: '1990-01-01', sex: 'Male', mrn: 'MRN001', tabs: [] }
    const vars = await buildPatientVariables('fhir-123', patient)
    expect(vars.patient_info.content).toContain('John Doe')
    expect(vars.patient_info.content).toContain('1990-01-01')
    expect(vars.patient_info.content).toContain('Male')
    expect(vars.patient_info.content).toContain('MRN001')
  })

  it('formats medications with data', async () => {
    vi.mocked(searchFhirMedications).mockResolvedValue({
      medications: [
        { id: '1', name: 'Aspirin', dose: '81mg', route: 'oral', frequency: 'daily', status: 'active' },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.medications.content).toContain('Aspirin')
    expect(vars.medications.content).toContain('81mg')
    expect(vars.medications.content).toContain('active')
    expect(vars.medications.content).toContain('Medications (1)')
  })

  it('formats allergies with severity and reaction', async () => {
    vi.mocked(searchFhirAllergies).mockResolvedValue({
      allergies: [
        { id: '1', substance: 'Penicillin', category: 'medication', clinicalStatus: 'active', reaction: 'Rash', severity: 'mild' },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.allergies.content).toContain('Penicillin')
    expect(vars.allergies.content).toContain('Rash')
    expect(vars.allergies.content).toContain('mild')
  })

  it('formats conditions with ICD-10 codes', async () => {
    vi.mocked(searchFhirConditions).mockResolvedValue({
      conditions: [
        { id: '1', name: 'COPD', clinicalStatus: 'active', coding: { code: 'J44.1', system: 'ICD-10' }, onsetDate: '2020-01-01' },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.conditions.content).toContain('COPD')
    expect(vars.conditions.content).toContain('J44.1')
  })

  it('formats vitals with blood pressure', async () => {
    vi.mocked(searchFhirVitals).mockResolvedValue({
      vitals: [
        { id: '1', name: 'Blood Pressure', systolic: 120, diastolic: 80, effectiveDateTime: '2024-01-01' },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.vitals.content).toContain('120/80')
    expect(vars.vitals.content).toContain('mmHg')
  })

  it('formats vitals with single value', async () => {
    vi.mocked(searchFhirVitals).mockResolvedValue({
      vitals: [
        { id: '1', name: 'Heart Rate', value: 72, unit: 'bpm', effectiveDateTime: '2024-01-01' },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.vitals.content).toContain('72')
    expect(vars.vitals.content).toContain('bpm')
  })

  it('formats family history with deceased members', async () => {
    vi.mocked(searchFhirFamilyHistories).mockResolvedValue({
      members: [
        {
          id: '1', name: 'Father', relationshipDisplay: 'Father',
          deceased: true, deceasedAge: '65',
          conditions: [{ name: 'Heart Disease', onsetAge: '50' }],
        },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.family_history.content).toContain('Father')
    expect(vars.family_history.content).toContain('deceased')
    expect(vars.family_history.content).toContain('age 65')
    expect(vars.family_history.content).toContain('Heart Disease')
  })

  it('handles service errors gracefully (catch fallback)', async () => {
    vi.mocked(searchFhirMedications).mockRejectedValue(new Error('FHIR down'))
    vi.mocked(searchFhirAllergies).mockRejectedValue(new Error('FHIR down'))
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.medications.content).toContain('No medications on file')
    expect(vars.allergies.content).toContain('No allergies on file')
  })

  it('pinned variables are marked correctly', async () => {
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.patient_info.isPinned).toBe(true)
    expect(vars.medications.isPinned).toBe(true)
    expect(vars.allergies.isPinned).toBe(true)
    expect(vars.conditions.isPinned).toBe(true)
    expect(vars.vitals.isPinned).toBe(true)
    expect(vars.care_team.isPinned).toBe(false)
    expect(vars.labs.isPinned).toBe(false)
  })

  it('truncates long encounter note text', async () => {
    vi.mocked(searchFhirEncounters).mockResolvedValue({
      encounters: [
        {
          id: '1', encounterFhirId: 'e1', patientFhirId: 'p1',
          date: '2024-01-01', classDisplay: 'outpatient', status: 'finished',
          noteText: 'A'.repeat(300), isSigned: false,
        },
      ],
    })
    const vars = await buildPatientVariables('fhir-123')
    expect(vars.encounters.content).toContain('...')
  })
})
