'use client';

import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { Variable, Template } from '../types/variable';
import { Order } from '../types/order';
import { ChartReviewRequest } from '../types/chart-review';
import { mockVariables, mockTemplates } from '../data/mock-variables';
import { usePatient } from './PatientContext';
import { buildPatientVariables } from '../variable-formatters';

type RightPanelType = 'orders' | 'variables' | 'templates' | 'ai' | 'chartReview' | 'calendar' | 'chat' | null;

interface SidebarContextType {
  rightPanelOpen: boolean;
  rightPanelType: RightPanelType;
  setRightPanelType: (type: RightPanelType) => void;
  toggleRightPanel: (type?: RightPanelType) => void;
  variables: Record<string, Variable>;
  variablesLoading: boolean;
  refreshVariables: () => void;
  templates: Record<string, Template>;
  orders: Order[];
  addOrder: (order: Order) => void;
  removeOrder: (id: string) => void;
  addVariable: (name: string, content: string, isPinned?: boolean) => void;
  updateVariable: (name: string, content: string) => void;
  deleteVariable: (name: string) => void;
  toggleVariablePin: (name: string) => void;
  chartReviewContent: ChartReviewRequest | null;
  setChartReviewContent: (content: ChartReviewRequest | null) => void;
  addTemplate: (name: string, content: string) => void;
}

const SidebarContext = createContext<SidebarContextType | undefined>(undefined);

export function SidebarProvider({ children }: { children: ReactNode }) {
  const [rightPanelOpen, setRightPanelOpen] = useState(false);
  const [rightPanelType, setRightPanelTypeState] = useState<RightPanelType>('orders');
  const [variablesByPatient, setVariablesByPatient] = useState<Record<string, Record<string, Variable>>>({});
  const [variablesLoading, setVariablesLoading] = useState(false);
  const [templates, setTemplates] = useState<Record<string, Template>>(mockTemplates);
  const { activePatientId, activePatient } = usePatient();
  const [ordersByPatient, setOrdersByPatient] = useState<Record<string, Order[]>>({});
  const [chartReviewContent, setChartReviewContent] = useState<ChartReviewRequest | null>(null);
  const orders = activePatientId ? (ordersByPatient[activePatientId] ?? []) : [];

  // Derive variables for the active patient — fall back to mock data for non-FHIR patients
  const variables = activePatientId
    ? (variablesByPatient[activePatientId] ?? mockVariables)
    : mockVariables;

  // Fetch FHIR variables when patient changes
  const fetchVariablesForPatient = useCallback(async (patientId: string, fhirId: string) => {
    setVariablesLoading(true);
    try {
      const autoVars = await buildPatientVariables(fhirId, activePatient);
      setVariablesByPatient(prev => {
        // Preserve any user-created (non-auto-generated) variables
        const existing = prev[patientId] ?? {};
        const userVars: Record<string, Variable> = {};
        for (const [key, v] of Object.entries(existing)) {
          if (!v.isAutoGenerated) {
            userVars[key] = v;
          }
        }
        return {
          ...prev,
          [patientId]: { ...autoVars, ...userVars },
        };
      });
    } finally {
      setVariablesLoading(false);
    }
  }, [activePatient]);

  // Auto-fetch when patient changes
  useEffect(() => {
    if (!activePatientId || !activePatient?.fhirId) return;

    // Skip if already fetched for this patient
    if (variablesByPatient[activePatientId]) return;

    fetchVariablesForPatient(activePatientId, activePatient.fhirId);
  }, [activePatientId, activePatient?.fhirId, variablesByPatient, fetchVariablesForPatient]);

  // Manual refresh
  const refreshVariables = useCallback(() => {
    if (!activePatientId || !activePatient?.fhirId) return;
    fetchVariablesForPatient(activePatientId, activePatient.fhirId);
  }, [activePatientId, activePatient?.fhirId, fetchVariablesForPatient]);

  const setRightPanelType = (type: RightPanelType) => {
    setRightPanelTypeState(type);
    if (type) {
      setRightPanelOpen(true);
    }
  };

  const toggleRightPanel = (type?: RightPanelType) => {
    if (type) {
      if (rightPanelType === type && rightPanelOpen) {
        setRightPanelOpen(false);
      } else {
        setRightPanelTypeState(type);
        setRightPanelOpen(true);
      }
    } else {
      if (!rightPanelOpen) {
        setRightPanelTypeState(rightPanelType || 'orders');
      }
      setRightPanelOpen(!rightPanelOpen);
    }
  };

  const addOrder = (order: Order) => {
    if (!activePatientId) return;
    setOrdersByPatient(prev => ({
      ...prev,
      [activePatientId]: [...(prev[activePatientId] ?? []), order],
    }));
  };

  const removeOrder = (id: string) => {
    if (!activePatientId) return;
    setOrdersByPatient(prev => ({
      ...prev,
      [activePatientId]: (prev[activePatientId] ?? []).filter(o => o.id !== id),
    }));
  };

  const addVariable = (name: string, content: string, isPinned: boolean = false) => {
    if (!activePatientId) return;
    setVariablesByPatient(prev => ({
      ...prev,
      [activePatientId]: {
        ...(prev[activePatientId] ?? mockVariables),
        [name]: { name, content, isPinned }
      }
    }));
  };

  const updateVariable = (name: string, content: string) => {
    if (!activePatientId) return;
    setVariablesByPatient(prev => {
      const current = prev[activePatientId] ?? mockVariables;
      return {
        ...prev,
        [activePatientId]: {
          ...current,
          [name]: { ...current[name], content }
        }
      };
    });
  };

  const deleteVariable = (name: string) => {
    if (!activePatientId) return;
    setVariablesByPatient(prev => {
      const current = { ...(prev[activePatientId] ?? mockVariables) };
      delete current[name];
      return { ...prev, [activePatientId]: current };
    });
  };

  const toggleVariablePin = (name: string) => {
    if (!activePatientId) return;
    setVariablesByPatient(prev => {
      const current = prev[activePatientId] ?? mockVariables;
      return {
        ...prev,
        [activePatientId]: {
          ...current,
          [name]: { ...current[name], isPinned: !current[name]?.isPinned }
        }
      };
    });
  };

  const addTemplate = (name: string, content: string) => {
    const key = name.toLowerCase().replace(/\s+/g, '_');
    setTemplates(prev => ({
      ...prev,
      [key]: { name: key, content, isPinned: false }
    }));
  };

  return (
    <SidebarContext.Provider
      value={{
        rightPanelOpen,
        rightPanelType,
        setRightPanelType,
        toggleRightPanel,
        variables,
        variablesLoading,
        refreshVariables,
        templates,
        orders,
        addOrder,
        removeOrder,
        addVariable,
        updateVariable,
        deleteVariable,
        toggleVariablePin,
        chartReviewContent,
        setChartReviewContent,
        addTemplate
      }}
    >
      {children}
    </SidebarContext.Provider>
  );
}

export function useSidebar() {
  const context = useContext(SidebarContext);
  if (!context) {
    throw new Error('useSidebar must be used within SidebarProvider');
  }
  return context;
}
